### ISSUE TITLE
pybullet: AttributeError: 'dict' object has no attribute 'env_specs'

### ISSUE THREAD

**Issue by james-coder** [neureal/neureal-ai-agent#2]
This is the error I get when running agent.py:

```
(base) james-coder@nvidia-docker:~/git/neureal-ai-agent$ ./build.sh build
...
(base) james-coder@nvidia-docker:~/git/neureal-ai-agent$ ./build.sh dev
root@b14173f046e7:/app# ls    
Dockerfile  LICENSE  README.md  agent-a2c.py  agent.py  build.sh  envs_local  neureal-ai-util  requirements.txt
root@b14173f046e7:/app# python agent.py
Traceback (most recent call last):
  File "agent.py", line 12, in <module>
    import pybullet_envs
  File "/usr/local/lib/python3.8/dist-packages/pybullet_envs/__init__.py", line 14, in <module>
    register(
  File "/usr/local/lib/python3.8/dist-packages/pybullet_envs/__init__.py", line 6, in register
    if id in registry.env_specs:
AttributeError: 'dict' object has no attribute 'env_specs'
root@b14173f046e7:/app# 
```

**Comment by james-coder** [comment]
Nothing specific with the app doing this, it's just the library or environment:
```
root@b14173f046e7:/app# pip install --upgrade --force-reinstall pybullet==3.2.5
Collecting pybullet==3.2.5
  Downloading pybullet-3.2.5-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (91.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.7/91.7 MB 25.2 MB/s eta 0:00:00
Installing collected packages: pybullet
  Attempting uninstall: pybullet
    Found existing installation: pybullet 3.2.5
    Uninstalling pybullet-3.2.5:
      Successfully uninstalled pybullet-3.2.5
Successfully installed pybullet-3.2.5
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
root@b14173f046e7:/app# python
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pybullet
pybullet build time: May 20 2022 19:44:17
>>> import pybullet_envs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/pybullet_envs/__init__.py", line 14, in <module>
    register(
  File "/usr/local/lib/python3.8/dist-packages/pybullet_envs/__init__.py", line 6, in register
    if id in registry.env_specs:
AttributeError: 'dict' object has no attribute 'env_specs'
>>> 
```
I have tried this on a different computer and had the same results. I think the next thing to try is to cycle through different dists and python versions and possibly find one where this error isn't an issue.

Above "AttributeError" happens with:
* PyBullet 3.2.5
* Python module gym 0.26.1 (pybullet dependency)
* Debian 11 / Python 3.9.2, 3.9.12
* Ubuntu 18.04.6 LTS / Python 3.6.9
* Ubuntu 20.04.4 LTS / Python 3.8.10 (which is based on Debian 11)

**Comment by james-coder** [comment]
~~At this point, I suspect that PyBullet 3.2.5 might be the cause. @wilbown what version of pybullet do you have? 3.2.5 is just the most recent.~~

**Comment by wilbown** [comment]
The guy who took over gym made breaking changes to it recently and that environment probably has not updated. I am using gym 0.24.1 and at least the basic environments (cartpole, lunarlander) still work. Lets just stick with gym 0.24.1 for now since it at least runs without error.

**Comment by james-coder** [comment]
Running through the Dockerfile in a few different ways (testing Ubuntu 18.04 instead of Ubuntu 20.04 for instance), and running pip install pybullet in a few different ways led to me finding that gym 0.26 is the problem. (gym 0.21.0 looks to be the most recent version that's stable.)

If you install gym 0.26? or anything +/- of that, they add a warning saying "We know there are problems here, upgrade to at least 0.25.1 to solve them." Unfortunately, I tried all higher versions and non worked with pybullet. They must have introduced some breaking changes.

**Comment by wilbown** [comment]
I tried a bunch of other environments in there and some more were broken. They changed the main interface itself and non backward compatible so lets just give them some time to work it out. We can always comment out optional environment imports like that if they are not working.

**Comment by james-coder** [comment]
@wilbown I think we posted at the same time, but I tried 0.24.1 one more time, since you specifically named it:
```
root@0c546fd6a269:/app# pip install gym==0.24.1
Collecting gym==0.24.1
  Downloading gym-0.24.1.tar.gz (696 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 696.4/696.4 kB 6.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting gym-notices>=0.0.4
  Downloading gym_notices-0.0.8-py3-none-any.whl (3.0 kB)
Requirement already satisfied: numpy>=1.18.0 in /usr/local/lib/python3.8/dist-packages (from gym==0.24.1) (1.23.3)
Requirement already satisfied: cloudpickle>=1.2.0 in /usr/local/lib/python3.8/dist-packages (from gym==0.24.1) (2.2.0)
Requirement already satisfied: importlib-metadata>=4.8.0 in /usr/local/lib/python3.8/dist-packages (from gym==0.24.1) (5.0.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.8/dist-packages (from importlib-metadata>=4.8.0->gym==0.24.1) (3.8.1)
Building wheels for collected packages: gym
  Building wheel for gym (pyproject.toml) ... done
  Created wheel for gym: filename=gym-0.24.1-py3-none-any.whl size=793137 sha256=2b8f496a24830090c92d5c63dbf4c88e95300f4c0fb67a12982449c806906a86
  Stored in directory: /root/.cache/pip/wheels/5a/e9/0b/5536e77ed2edbbf067ecff287ec039633d40daee4d8dac7716
Successfully built gym
Installing collected packages: gym-notices, gym
  Attempting uninstall: gym
    Found existing installation: gym 0.21.0
    Uninstalling gym-0.21.0:
      Successfully uninstalled gym-0.21.0
Successfully installed gym-0.24.1 gym-notices-0.0.8
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
root@0c546fd6a269:/app# python3
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pybullet_envs
Warning: Gym version v0.24.1 has a number of critical issues with `gym.make` such that environment observation and action spaces are incorrectly evaluated, raising incorrect errors and warning . It is recommend to downgrading to v0.23.1 or upgrading to v0.25.1
/usr/local/lib/python3.8/dist-packages/gym/envs/registration.py:415: UserWarning: WARN: The `registry.env_specs` property along with `EnvSpecTree` is deprecated. Please use `registry` directly as a dictionary instead.
  logger.warn(
>>>
```

**Comment by wilbown** [comment]
Gym 0.23.1 should be fine too. I will downgrade to that to check.

**Comment by james-coder** [comment]
Gym 0.23.1 successful import test! :partying_face: 
https://github.com/neureal/neureal-ai-agent/pull/1/commits/8361583292c7ff724d5f7b898e7dca49b611aa3f

**Comment by james-coder** [comment]
Hrm.......... :thinking: 
[PR for "compatibility with Gym 0.26.0"](https://github.com/bulletphysics/bullet3/pull/4335)
Looks like we'll just want to revisit this specific item later. https://github.com/neureal/neureal-ai-agent/pull/1/commits/3a8b31da41c0474c327d0461876c3cc533104638
