### ISSUE TITLE
RuntimeError: Physical devices cannot be modified after being initialized

### ISSUE THREAD

**Issue by james-coder** [neureal/neureal-ai-agent#3]
I just tried running agent.py again and now I get this output:
```
(base) james-coder@nvidia-docker:~/git/neureal-ai-agent$ ./build.sh dev
root@3390e2979adb:/app# python agent.py
2022-10-03 06:05:46.165259: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-03 06:05:46.214256: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-03 06:05:46.214494: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-03 06:05:46.215381: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-03 06:05:46.216306: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-03 06:05:46.216494: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-03 06:05:46.216672: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-03 06:05:46.728145: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-03 06:05:46.728443: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-03 06:05:46.728632: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-03 06:05:46.728861: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 22291 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3090 Ti, pci bus id: 0000:06:10.0, compute capability: 8.6
Traceback (most recent call last):
  File "agent.py", line 34, in <module>
    tf.config.experimental.set_memory_growth(physical_devices_gpu[i], True)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/config.py", line 716, in set_memory_growth
    context.context().set_memory_growth(device, enable)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/context.py", line 1649, in set_memory_growth
    raise RuntimeError(
RuntimeError: Physical devices cannot be modified after being initialized
root@3390e2979adb:/app# 
```

Caused by agent.py:34:
```
for i in range(len(physical_devices_gpu)):
    tf.config.experimental.set_memory_growth(physical_devices_gpu[i], True)
```

This may have been caused by me re-ordering things from the original agent.py.

**Comment by james-coder** [comment]
Resolved in https://github.com/neureal/neureal-ai-agent/pull/1/commits/c0da55735403b0bb33c14926cf4b5ef16717fe9e

(Could not figure out what model_nets.py was doing or included that caused the GPU to be accessed, but switched around the right parts in the import section so it works.)
